import Head from "next/head";
import Image from "next/image";
import LatestBlogs from "../components/LatestBlogs";
import RightSection from "../components/RightSection";
import styles from "../styles/Home.module.css";
import FeaturedPosts from "../components/FeaturedPosts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>AniLog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto p-8">
        <FeaturedPosts />
        <section className={styles.home_grid}>
          <LatestBlogs />
          <RightSection />
        </section>
      </main>
    </div>
  );
}
